### ISSUE TITLE
Adding a yarn.lock

### ISSUE THREAD

**Issue by GuillaumeOj** [Mergifyio/react-crisp#41]
According to yarn docs, the `yarn.lock` file should be checked into source control.
https://classic.yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control)
What do you think of this ?

**Comment by jd** [comment]
This is true for application, but not for library I presume.

**Comment by GuillaumeOj** [comment]
It seems they recommended it for libraries too:
> Framework and library authors should also check yarn.lock into source control. Don’t worry about publishing the yarn.lock file as it won’t have any effect on users of the library.

**Comment by jd** [comment]
Interesting. What'd be the point if you don't publish it?

**Comment by GuillaumeOj** [comment]
From what I've read here [in this detailed explanation](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) about the lockfile, they recommend to use the lock file for the dev dependencies.

> Without lockfiles it gets even more complicated: In applications or libraries, if there is no lockfile, you will have to check the dependencies every time you install or re-install them and make sure that everything still works. Otherwise the build might be broken or the tests might fail.

In our case the risk seems to be small since we don't commit new code every day.
However it looks to be a good practice for the dev dependencies to use and commit a lock file.

I'm sorry if I just quote. As this project is my first public package, I've no experience about the consequences of not committing a lockfile in a JS library.

**Comment by jd** [comment]
Thanks for the blog post! As I understand it, it's only used for developers working on the project and that want a repeatable deployment for their dev env. And it's not used by end users.

Why not. In that case, it should be updated and maintained with dependabot though.
